SOLAR_SLUG = '/solar'
GLOBAL_WARMING_SLUG = '/global-warming'
TICKER_SLUG = '/ticker'
USER_SLUG='/user'
LIFE_EXPECTANCY_SLUG='/life'
TERMS_AND_CONDITIONS_SLUG='/terms'


NAVBAR_PAGES = ( SOLAR_SLUG, GLOBAL_WARMING_SLUG, TICKER_SLUG, LIFE_EXPECTANCY_SLUG)
